# Generated by Django 3.2.7 on 2026-09-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web", "0042_project_show_in_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Tipo de matrícula",
                "verbose_name_plural": "Tipos de matrícula",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VehiclePlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate", models.CharField(max_length=20, verbose_name="Matrícula")),
                (
                    "plate_normalized",
                    models.CharField(editable=False, max_length=20, verbose_name="Matrícula normalizada"),
                ),
                (
                    "plate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicle_plates",
                        to="vehicle_access.platetype",
                        verbose_name="Tipo de matrícula",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_plates",
                        to="web.project",
                        to_field="uuid",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula de vehículo",
                "verbose_name_plural": "Matrículas de vehículos",
                "ordering": ["project", "plate_normalized"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "plate_normalized"),
                        name="vehicle_access_unique_plate_project",
                    )
                ],
            },
        ),
    ]
