# Generated by Django 3.2.7 on 2026-09-08 13:05

from django.db import migrations, models
import project_pwa.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ProjectPWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=project_pwa.models.pwa_logo_path)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_uuid', models.CharField(db_index=True, max_length=255, verbose_name='Project UUID')),
            ],
            options={
                'verbose_name': 'Project PWA',
                'verbose_name_plural': 'Project PWAs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
