# Generated by Django 3.2.7 on 2026-09-08 13:54

from django.db import migrations, models
import project_pwa.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_pwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpwa',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=project_pwa.models.pwa_background_path),
        ),
    ]
